name: SimpleRestart
main: com.hamaluik.SimpleRestart.SimpleRestart
version: 1.3.0
author: FuzzyWuzzie, THExSYSTEM
softdepend: [Permissions]
commands:
   restart:
      description: restart the server!
      usage: |
            usage:
                /restart now
   reboot:
      description: restart the server!
      usage: |
            usage:
                /reboot now
   memory:
      description: gives memory usage information
      usage: |
            usage:
                /memory