name: SimpleRestart
main: com.hamaluik.SimpleRestart.SimpleRestart
version: 1.3.1
authors:
  - "FuzzyWuzzie"
  - "THExSYSTEM"
website: "http://dev.bukkit.org/server-mods/simple_restart/"
database: false
load: postworld
softdepend: [Permissions]
commands:
   restart:
      description: restart the server!
      usage: |
            usage:
                /restart now
   reboot:
      description: restart the server!
      usage: |
            usage:
                /reboot now
   memory:
      description: gives memory usage information
      usage: |
            usage:
                /memory